global:
  scrape_interval: 5s
  external_labels:
    namespace: local

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          container: 'prometheus'

  - job_name: pushgateway
    static_configs:
      - targets: [ 'pushgateway:9091' ]
        labels:
          container: 'pushgateway'

